org.joget.JsonPostTool.pluginDesc=Post to a JSON feed URL, and inserts formatted data into form data table or workflow variable
org.joget.JsonPostTool.pluginLabel=Json Post Tool
app.jsontool.postAsJson=Post Parameters as JSON Payload
app.postFormJson.header=Request Headers
app.postFormJson.header.name=Name
app.postFormJson.header.value=Value